apiVersion: k8se.microsoft.com/v1alpha1
kind: ContainerApp
metadata:
  name: containerapp-sample
  namespace: k8se-apps
spec:
  configuration:
    ingress:
      external: true
      targetPort: 80
  template:
    containers:
    - image: index.docker.io/showpune/cartographer-zhiyongli-zhiyongli-java-containerapp@sha256:ca4bf13cfa8da31eb6905dda81c4e94bd179db0e062d41cd6330127d9ee766d9
      name: nginx
      env:
      - name: HTTP_PORT
        value: '80'
      resources:
        cpu: "0.5"
        memory: "250Mi"
