apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"7"},"creationTimestamp":"2022-06-17T08:52:20Z","generation":7,"labels":{"app.kubernetes.io/component":"cartographer","app.kubernetes.io/name":"cartographer-controller","app.kubernetes.io/version":"v0.0.0-dev"},"name":"cartographer-controller","namespace":"cartographer-system","resourceVersion":"41451765","uid":"e47d6575-09da-42c0-908f-0fd814f581d1"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"cartographer-controller"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"cartographer-controller"}},"spec":{"containers":[{"args":["-cert-dir=/cert"],"image":"showpune/cartographer:latest","imagePullPolicy":"Always","name":"cartographer-controller","resources":{"limits":{"cpu":"200m","memory":"256Mi"},"requests":{"cpu":"200m","memory":"256Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["all"]},"readOnlyRootFilesystem":true,"runAsNonRoot":true},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/cert","name":"cert","readOnly":true}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"cartographer-controller","serviceAccountName":"cartographer-controller","terminationGracePeriodSeconds":30,"volumes":[{"name":"cert","secret":{"defaultMode":420,"secretName":"cartographer-webhook"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2022-06-17T08:52:20Z","lastUpdateTime":"2022-07-19T07:53:14Z","message":"ReplicaSet \"cartographer-controller-7fb785dd6f\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2022-07-20T08:38:31Z","lastUpdateTime":"2022-07-20T08:38:31Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":7,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2022-06-17T08:52:20Z"
  generation: 8
  labels:
    app.kubernetes.io/component: cartographer
    app.kubernetes.io/name: cartographer-controller
    app.kubernetes.io/version: v0.0.0-dev
  name: cartographer-controller
  namespace: cartographer-system
  resourceVersion: "43341482"
  uid: e47d6575-09da-42c0-908f-0fd814f581d1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cartographer-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cartographer-controller
    spec:
      containers:
      - args:
        - -cert-dir=/cert
        image: showpune/cartographer:latest
        imagePullPolicy: Always
        env:
        - name: WORK_NAMESPCE
          value: "cluster"
        name: cartographer-controller
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cert
          name: cert
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cartographer-controller
      serviceAccountName: cartographer-controller
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: cartographer-webhook
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-07-20T08:38:31Z"
    lastUpdateTime: "2022-07-20T08:38:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-06-17T08:52:20Z"
    lastUpdateTime: "2022-07-21T13:21:55Z"
    message: ReplicaSet "cartographer-controller-7f9b96cb6b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
