apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kapp-controller.carvel.dev/version: v0.38.4
    kbld.k14s.io/images: |
      - origins:
        - local:
            path: /home/runner/work/carvel-kapp-controller/carvel-kapp-controller
        - git:
            dirty: false
            remoteURL: https://github.com/vmware-tanzu/carvel-kapp-controller
            sha: cf8fc08cafd1893f5a9006cfdfbd3d1c42878941
            tags:
            - v0.38.4
        url: ghcr.io/vmware-tanzu/carvel-kapp-controller@sha256:fb1345342c98fb1f88ffdc3a4ec35228404abff0c528fabf7bead33a2564854c
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"4","kapp-controller.carvel.dev/version":"v0.38.4","kbld.k14s.io/images":"- origins:\n  - local:\n      path: /home/runner/work/carvel-kapp-controller/carvel-kapp-controller\n  - git:\n      dirty: false\n      remoteURL: https://github.com/vmware-tanzu/carvel-kapp-controller\n      sha: cf8fc08cafd1893f5a9006cfdfbd3d1c42878941\n      tags:\n      - v0.38.4\n  url: ghcr.io/vmware-tanzu/carvel-kapp-controller@sha256:fb1345342c98fb1f88ffdc3a4ec35228404abff0c528fabf7bead33a2564854c\n"},"creationTimestamp":"2022-07-11T17:28:26Z","generation":17,"name":"kapp-controller","namespace":"kapp-controller","resourceVersion":"25185968","uid":"f422ce36-2ddc-4f31-978a-88997c5c01a0"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":0,"selector":{"matchLabels":{"app":"kapp-controller"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"kapp-controller"}},"spec":{"containers":[{"args":["-packaging-global-namespace=kapp-controller-packaging-global","-enable-api-priority-and-fairness=True"],"env":[{"name":"KAPPCTRL_MEM_TMP_DIR","value":"/etc/kappctrl-mem-tmp"},{"name":"KAPPCTRL_SIDECAREXEC_SOCK","value":"/etc/kappctrl-mem-tmp/sidecarexec.sock"},{"name":"KAPPCTRL_SYSTEM_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}},{"name":"KAPPCTRL_API_PORT","value":"10350"}],"image":"ghcr.io/vmware-tanzu/carvel-kapp-controller@sha256:fb1345342c98fb1f88ffdc3a4ec35228404abff0c528fabf7bead33a2564854c","imagePullPolicy":"IfNotPresent","name":"kapp-controller","ports":[{"containerPort":10350,"name":"api","protocol":"TCP"}],"resources":{"requests":{"cpu":"500m","memory":"500m"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["all"]},"readOnlyRootFilesystem":true,"runAsNonRoot":true},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/etc/kappctrl-mem-tmp","name":"template-fs"},{"mountPath":"/home/kapp-controller","name":"home"}]},{"command":["/kapp-controller-sidecarexec"],"env":[{"name":"KAPPCTRL_SIDECAREXEC_SOCK","value":"/etc/kappctrl-mem-tmp/sidecarexec.sock"}],"image":"ghcr.io/vmware-tanzu/carvel-kapp-controller@sha256:fb1345342c98fb1f88ffdc3a4ec35228404abff0c528fabf7bead33a2564854c","imagePullPolicy":"IfNotPresent","name":"kapp-controller-sidecarexec","resources":{"requests":{"cpu":"120m","memory":"100Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["all"]},"readOnlyRootFilesystem":false,"runAsNonRoot":true},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/etc/kappctrl-mem-tmp","name":"template-fs"},{"mountPath":"/home/kapp-controller","name":"home"},{"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount","name":"empty-sa"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"kapp-controller-sa","serviceAccountName":"kapp-controller-sa","terminationGracePeriodSeconds":30,"volumes":[{"emptyDir":{"medium":"Memory"},"name":"template-fs"},{"emptyDir":{"medium":"Memory"},"name":"home"},{"emptyDir":{},"name":"empty-sa"}]}}},"status":{"availableReplicas":5,"conditions":[{"lastTransitionTime":"2022-07-11T17:28:26Z","lastUpdateTime":"2022-07-12T06:33:06Z","message":"ReplicaSet \"kapp-controller-8596c4d545\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2022-07-12T07:52:48Z","lastUpdateTime":"2022-07-12T07:52:48Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":17,"readyReplicas":5,"replicas":5,"updatedReplicas":5}}
  creationTimestamp: "2022-07-11T17:28:26Z"
  generation: 18
  name: kapp-controller
  namespace: kapp-controller
  resourceVersion: "25219720"
  uid: f422ce36-2ddc-4f31-978a-88997c5c01a0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: kapp-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kapp-controller
    spec:
      containers:
      - args:
        - -packaging-global-namespace=kapp-controller-packaging-global
        - -enable-api-priority-and-fairness=True
        env:
        - name: KAPPCTRL_MEM_TMP_DIR
          value: /etc/kappctrl-mem-tmp
        - name: KAPPCTRL_SIDECAREXEC_SOCK
          value: /etc/kappctrl-mem-tmp/sidecarexec.sock
        - name: KAPPCTRL_SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KAPPCTRL_API_PORT
          value: "10350"
        image: ghcr.io/vmware-tanzu/carvel-kapp-controller@sha256:fb1345342c98fb1f88ffdc3a4ec35228404abff0c528fabf7bead33a2564854c
        imagePullPolicy: IfNotPresent
        name: kapp-controller
        ports:
        - containerPort: 10350
          name: api
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 500m
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kappctrl-mem-tmp
          name: template-fs
        - mountPath: /home/kapp-controller
          name: home
      - command:
        - /kapp-controller-sidecarexec
        env:
        - name: KAPPCTRL_SIDECAREXEC_SOCK
          value: /etc/kappctrl-mem-tmp/sidecarexec.sock
        image: ghcr.io/vmware-tanzu/carvel-kapp-controller@sha256:fb1345342c98fb1f88ffdc3a4ec35228404abff0c528fabf7bead33a2564854c
        imagePullPolicy: IfNotPresent
        name: kapp-controller-sidecarexec
        resources:
          requests:
            cpu: 120m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kappctrl-mem-tmp
          name: template-fs
        - mountPath: /home/kapp-controller
          name: home
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: empty-sa
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kapp-controller-sa
      serviceAccountName: kapp-controller-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: template-fs
      - emptyDir:
          medium: Memory
        name: home
      - emptyDir: {}
        name: empty-sa
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2022-07-11T17:28:26Z"
    lastUpdateTime: "2022-07-12T06:33:06Z"
    message: ReplicaSet "kapp-controller-8596c4d545" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-07-12T07:52:48Z"
    lastUpdateTime: "2022-07-12T07:52:48Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 18
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
