apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: currentNS-java-directjar
  labels:
    app.tanzu.vmware.com/workload-type: web-directjar
spec:
  serviceAccountName: namespace-service-account
  params:
    - name: image_prefix
      value: showpune/cartographer-currentNS-
    - name: jar_source
      value: https://mssdevsharedstorage.file.core.windows.net/zhiyongtest/directjar/java-native-0.0.1-SNAPSHOT.jar?se=2022-10-08T13%3A41%3A41Z&sp=r&sv=2018-11-09&sr=f&sig=%2Bi6VT3kJC7zGuokJtYAq43JEKW2E1sR3y5H86/2xreo%3D