---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartographer-controller
  namespace: zhiyong
  labels:
    app.kubernetes.io/component: cartographer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cartographer-user-admin
  labels:
    app.kubernetes.io/component: cartographer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cartographer-controller-admin
subjects:
  - kind: ServiceAccount
    name: cartographer-controller
    namespace: zhiyong

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartographer-controller
  namespace: zhiyong
  labels:
    app.kubernetes.io/name: cartographer-controller
    app.kubernetes.io/version: v0.0.0-dev
    app.kubernetes.io/component: cartographer
spec:
  selector:
    matchLabels:
      app: cartographer-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: cartographer-controller
    spec:
      serviceAccount: cartographer-controller
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: cartographer-webhook
      containers:
        - name: cartographer-controller
          image: showpune/cartographer@sha256:df3882dad2f6bbbe762d3e241888db64aa21d958d18c0522dbacd7fe283f204a
          env:
            - name: CARTOGRAPHER_WORK_NAMESPCE
              value: zhiyong
          args:
            - -cert-dir=/cert
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - all
          volumeMounts:
            - mountPath: /cert
              name: cert
              readOnly: true
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi